return {
    "4-LOM",
    "Aayla Secura",
    "Admiral Thrawn",
    "Ahsoka Tano",
    "Anakin Solo",
    "Asajj Ventress",
    "Aurra Sing",
    "Senator Bail Organa",
    "Barriss Offee",
    "Bastila Shan",
    "Ben Skywalker",
    "Bib Fortuna",
    "Biggs Darklighter",
    "Boba Fett",
    "Bossk",
    "Brakiss",
    "C-3PO",
    "Cad Bane",
    "Cade Skywalker",
    "Callista Ming",
    "Captain Rex",
    "Carnor Jax",
    "Chewbacca",
    "Clone Commander Cody",
    "Count Dooku",
    "Darth Bane",
    "Darth Krayt",
    "Darth Vader",
    "Han Solo",
    "Jabba the Hutt",
    "Luke Skywalker",
    "Plo Koon",
    "Pre Vizsla",
    "Prince Xizor",
    "Princess leia",
    "PROXY",
    "Qui-Gon Jinn",
    "Quinlan Vos",
    "R2-D2",
    "Rahm Kota",
    "Revan",
    "Satele Shan",
    "Savage Opress",
    "Sebulba",
    "Shaak Ti",
    "Shmi Skywalker",
    "Talon Karrde",
    "Ulic Qel-Droma",
    "Visas Marr",
    "Watto",
    "Wedge Antilles",
    "Yoda",
    "Zam Wessel",
    "Zayne Carrick",
    "Zuckuss"
}
